version: '3.8'

services:
  bot:
    container_name: 'facebook_apps_bot'
    build: .
    image: 'bots/facebook_apps'
    volumes:
      - ./data:/opt/facebook_apps_bot/data
    env_file: '.env'
    restart: always
